FROM debian:testing AS installer

# whether to install documentation and/or source files
# this has to be yes or no
ARG DOCFILES=no
ARG SRCFILES=no

# the mirror from which we will download TeX Live
ARG TLMIRRORURL

# install required setup dependencies
RUN apt-get update && \
  apt-get install -qy --no-install-recommends \
  gpg gpg-agent perl rsync sed tar

# download and verify TL installer before extracting archive
WORKDIR /
RUN echo "Fetching installation from mirror $TLMIRRORURL" && \
  rsync -a --stats "$TLMIRRORURL" texlive

WORKDIR /texlive
RUN --network=none if ! [ -f install-tl ]; then \
    # debug output for potential bad rsync fetches
    ls -lisa; \
  fi && \
  # create installation profile for full scheme installation with
  # the selected options
  echo "Building with documentation: $DOCFILES" && \
  echo "Building with sources: $SRCFILES" && \
  # choose complete installation
  echo "selected_scheme scheme-full" > install.profile && \
  # … but disable documentation and source files when asked to stay slim
  if [ "$DOCFILES" = "no" ]; then echo "tlpdbopt_install_docfiles 0" >> install.profile && \
    echo "BUILD: Disabling documentation files"; fi && \
  if [ "$SRCFILES" = "no" ]; then echo "tlpdbopt_install_srcfiles 0" >> install.profile && \
    echo "BUILD: Disabling source files"; fi && \
  echo "tlpdbopt_autobackup 0" >> install.profile && \
  # furthermore we want our symlinks in the system binary folder to avoid
  # fiddling around with the PATH
  echo "tlpdbopt_sys_bin /usr/bin" >> install.profile && \
  # actually install TeX Live
  ./install-tl -profile install.profile

# create data image containing only the TeX Live installation
FROM scratch
COPY --link --from=installer /usr/local/texlive /usr/local/texlive

LABEL org.opencontainers.image.authors="Island of TeX" \
  org.opencontainers.image.url=https://gitlab.com/islandoftex/images/texlive \
  org.opencontainers.image.source=https://gitlab.com/islandoftex/images/texlive/-/blob/master/Dockerfile.tree
